ESTRUTURA DO TIPO SEQUENCIA: Lista, Tuplas, Set, Dicionario

LISTA , é mutável

Em Python, as listas podem ser construídas de várias maneiras:

• Usando um par de colchetes para denotar uma lista vazia: lista1 = []

• Usando um par de colchetes e elementos separados por vírgulas: lista2 = ['a', 'b', 'c']

• Usando uma "list comprehension": [x for x in iterable]

• Usando o construtor de tipo: list()

In [30]:
nome = ['j','o','n','a','t','h','a','s']
for i in nome:
    print(nome.index(i), i) #função index retorna a posição de um elemento  em uma lista

0 j
1 o
2 n
3 a
4 t
5 h
3 a
7 s


Função split() , pode se usada para transformar um texto em uma lista, dicionario 

In [85]:
texto = "Dato;Carneiro;dos;santos"
print("quantas letras a?:", "a" in texto)
print("quantas letras a?:", texto.count("a"))
lista = texto.split(";") #o delimitador aqui é o ;, mas poderia ser qualquer caracter
print(lista)
print()

frutas = ["maça", "banana", "uva", "mamão", "maça"]
notas = [8.7, 5.2, 10, 3.5]
print("maça" in frutas) # True
print("abacate" in frutas) # False
print("abacate" not in frutas) # True
print(min(frutas)) # banana
print(max(notas)) # 10
print(frutas.count("maça")) # 2
print(frutas + notas)
print(2 * frutas)

quantas letras a?: True
quantas letras a?: 3
['Dato', 'Carneiro', 'dos', 'santos']

True
False
True
banana
10
2
['maça', 'banana', 'uva', 'mamão', 'maça', 8.7, 5.2, 10, 3.5]
['maça', 'banana', 'uva', 'mamão', 'maça', 'maça', 'banana', 'uva', 'mamão', 'maça']


LIST COMPREHENSION (COMPREENSÕES DE LISTA)
Esse tipo de técnica é utilizada quando, dada 
uma sequência, deseja-se criar uma nova sequência, porém com as informações 
originais transformadas ou filtradas por um critério. Para entender essa técnica, vamos 

In [88]:
linguagens = ["Python", "Java", "JavaScript", "C", "C#", "C++",
"Swift", "Go", "Kotlin"]

'''linguagens = Python Java JavaScript C C# C++ Swift Go Kotlin.split()  Essa sintaxe produz o mesmo resultado que a linha 1'''

print("Antes da listcomp = ", linguagens)
linguagens = [item.lower() for item in linguagens]
print("\nDepois da listcomp = ", linguagens)


Antes da listcomp =  ['Python', 'Java', 'JavaScript', 'C', 'C#', 'C++', 'Swift', 'Go', 'Kotlin']

Depois da listcomp =  ['python', 'java', 'javascript', 'c', 'c#', 'c++', 'swift', 'go', 'kotlin']


FUNÇÕES MAP() E FILTER() 

A função map() é utilizada para aplicar 
uma determinada função em cada item de um objeto iterável. Para que essa 
transformação seja feita, a função map() exige que sejam passados dois parâmetros (map é bem parecida com a listcomp)

In [98]:
# Exemplo 1
print("Exemplo 1")
linguagens = "Python Java JavaScript C C# C++ Swift Go Kotlin".split()
print(linguagens)
nova_lista = map(lambda x: x.lower(), linguagens) # função lambda, é que a função é é chamada somente 1x
print(f"A nova lista é = {nova_lista}\n")
nova_lista = list(nova_lista)
print(f"Agora sim, a nova lista é = {nova_lista}")

Exemplo 1
['Python', 'Java', 'JavaScript', 'C', 'C#', 'C++', 'Swift', 'Go', 'Kotlin']
A nova lista é = <map object at 0x00000186005770D0>

Agora sim, a nova lista é = ['python', 'java', 'javascript', 'c', 'c#', 'c++', 'swift', 'go', 'kotlin']


A função filter() tem as mesmas características da função map(), mas, em vez de 
usarmos uma função para transformar os valores da lista, nós a usamos para filtrar

In [103]:
numeros = list(range(0, 21))
numeros_pares = list(filter(lambda x: x % 2 == 0, numeros))
print(numeros_pares)



[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


TUPLA, é igual a uma lista , a diferença é que ela é IMUTÀVEL (não se altera)

Em Python, as tuplas podem ser construídas de três maneiras:

• Usando um par de parênteses para denotar uma tupla vazia: tupla1 = ()

• Usando um par de parênteses e elementos separados por vírgulas: tupla2 = ('a', 'b', 'c')

• Usando o construtor de tipo: tuple()


In [106]:
vogais = ('a', 'e', 'i', 'o', 'u')
print(f"Tipo do objeto vogais = {type(vogais)}")
for p, x in enumerate(vogais):
 print(f"Posição = {p}, valor = {x}")


Tipo do objeto vogais = <class 'tuple'>
Posição = 0, valor = a
Posição = 1, valor = e
Posição = 2, valor = i
Posição = 3, valor = o
Posição = 4, valor = u


OBJETO DO TIPO SET
 Um objeto do tipo set habilita operações matemáticas de 
conjuntos, tais como: união, intersecção, diferenteça, etc. Esse tipo de estrutura pode ser 
usado, portanto, em testes de associação e remoção de valores duplicados de uma 
sequência

OBJETOS DO TIPO MAPPING
As estruturas de dados que possuem um mapeamento entre uma chave e um valor são 
consideradas objetos do tipo mapping. Em Python, o objeto que possui essa propriedade 
é o dict (dicionário). Uma vez que esse objeto é mutável, conseguimos atribuir um 
novo valor a uma chave já existente.

Podemos construir dicionários em Python das seguintes maneiras:

• Usando um par de chaves para denotar um dict vazio: dicionario1 = {}

• Usando um par de elementos na forma, chave : valor separados por vírgulas: 
dicionario2 = {'one': 1, 'two': 2, 'three': 3}

• Usando o construtor de tipo: dict()

Observe os exemplos a seguir com maneiras de construir o dicionár


In [113]:
# Exemplo 1 - Criação de dicionário vazio, com atribuição posterior de chave e valor 
dici_1 = {}
dici_1['nome'] = "João"
dici_1['idade'] = 30
# Exemplo 2 - Criação de dicionário usando um par elementos na forma, chave : valor
dici_2 = {'nome': 'João', 'idade': 30}

# Exemplo 3 - Criação de dicionário com uma lista de tuplas. Cada tupla representa um par chave : valor
dici_3 = dict([('nome', "João"), ('idade', 30)])
# Exemplo 4 - Criação de dicionário com a função built-in zip() e duas listas, uma com as chaves, outra com os valores.
dici_4 = dict(zip(['nome', 'idade'], ["João", 30]))

print(dici_1 == dici_2 == dici_3 == dici_4) # Testando se as diferentes construções resultamo em objetos iguais.
True

True


True

OBJETOS DO TIPO ARRAY NUMPY
Quando o assunto é estrutura de dados em Python, não podemos deixar de falar dos 
objetos array numpy. Primeiramente, todas os objetos e funções que usamos até o 
momento fazem parte do core do interpretador Python, o que quer dizer que tudo está já 
instalado e pronto para usar. Além desses inúmeros recursos já disponíveis, podemos 
fazer um certo tipo de instalação e usar objetos e funções que outras 
pessoas/organizações desenvolveram e disponibilizaram de forma gratuita. Esse é o 
caso da biblioteca NumPy, criada especificamente para a computação científica com 

Python. O NumPy contém, entre outras coisas:

• Um poderoso objeto de matriz (array) N-dimensional.

• Funções sofisticadas.

• Ferramentas para integrar código C/C++ e Fortran.

• Recursos úteis de álgebra linear, transformação de Fourier e números aleatórios.

O endereço com a documentação completa da biblioteca NumPy está disponível 
em https://numpy.org/. Sem dúvida, o NumPy é a biblioteca mais poderosa para 
trabalhar com dados tabulares (matrizes), além de ser um recurso essencial para os 
desenvolvedores científicos, como os que desenvolvem soluções de inteligência 
artificial para imagens.
Para utilizar a biblioteca NumPy é preciso fazer a instalação com o comando pip 
install numpy. No entanto, se você estiver usando o projeto Anaconda, ou o Google 
Colab, esse recurso já estará instalado. Além da instalação, toda vez que for usar 
recusos da biblioteca, é necessário importar a biblioteca para o projeto, como o 
comando import numpy. Observe o códgio a seguir.

In [116]:
import numpy
matriz_1_1 = numpy.array([1, 2, 3]) # Cria matriz 1 linha e 1 coluna
matriz_2_2 = numpy.array([[1, 2], [3, 4]]) # Cria matriz 2 linhas e 2 colunas
matriz_3_2 = numpy.array([[1, 2], [3, 4], [5, 6]]) # Cria matriz 3 linhas e 2 colunas
matriz_2_3 = numpy.array([[1, 2, 3], [4, 5, 6]]) # Cria matriz 2 linhas e 3 colunas
print(type(matriz_1_1))
print('\n matriz_1_1 = ', matriz_1_1)
print('\n matriz_2_2 = \n', matriz_2_2)
print('\n matriz_3_2 = \n', matriz_3_2)
print('\n matriz_2_3 = \n', matriz_2_3)


<class 'numpy.ndarray'>

 matriz_1_1 =  [1 2 3]

 matriz_2_2 = 
 [[1 2]
 [3 4]]

 matriz_3_2 = 
 [[1 2]
 [3 4]
 [5 6]]

 matriz_2_3 = 
 [[1 2 3]
 [4 5 6]]
